import type { Metadata } from "next";
import Logo from '@/app/assets/white-logo.png';
import Image from 'next/image';
import '@/app/globals.css'

import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarHeader,
} from "@/components/ui/sidebar"
import Link from "next/link";
import { Header } from "./components/header";
import { Button } from "@/components/ui/button";
import LogoutAccount from "./components/logout";

export const metadata: Metadata = {
  title: "Article Page",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    {
      title: "Article",
      url: "article",
    },
    {
      title: "Category",
      url: "category",
    },
  ]

  return (
    <main className="">
      <SidebarProvider>
        <Sidebar className="pt-6 pb-4 bg-blue-600">
          <SidebarHeader className="px-8">
            <Image src={Logo} alt="image-logo" />
          </SidebarHeader>
          <SidebarContent>
            <SidebarGroup className="px-4">
              <SidebarGroupLabel className="text-white">Menu</SidebarGroupLabel>
              <SidebarGroupContent>
                <SidebarMenu>
                  {items.map((item) => (
                    <SidebarMenuItem key={item.title} className="hover:bg-blue-500 hover:rounded-[6px]">
                      <SidebarMenuButton asChild>
                        <Link href={`/admin/${item.url}`}>
                          <span className="text-white text-base leading-6 font-medium">{item.title}</span>
                        </Link>
                      </SidebarMenuButton>
                    </SidebarMenuItem>
                  ))}
                  <SidebarMenuItem>
                    <SidebarMenuButton className="hover:bg-blue-500 hover:cursor-pointer">
                      <div className="w-full">
                        <LogoutAccount />
                      </div>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                </SidebarMenu>
              </SidebarGroupContent>
            </SidebarGroup>
          </SidebarContent>
        </Sidebar>
        
        <section className="flex-1 flex flex-col bg-[#f3f4f6]">
          {/* Navbar */}
          <Header />

          {/* Main Content */}
          <div className="px-6 py-6">
            {children}
          </div>
        </section>
      </SidebarProvider>
    </main>
  );
}
