import type { Metadata } from "next";
import '@/app/globals.css'

export const metadata: Metadata = {
  title: "Admin | Article",
  description: "Generated by create next app",
};

export default function AdminArticleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-full bg-gray-50 border border-slate-200 rounded-[12px]">
        <div className="flex-1">
            {children}
        </div>
    </main>
  );
}
