import type { Metadata } from "next";
import '@/app/globals.css'

export const metadata: Metadata = {
  title: "Blogs App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen w-full bg-white sm:bg-gray-100 flex items-center justify-center">
        <div className="sm:bg-white w-[400px] rounded-[12px] py-[40px] px-[16px] flex flex-col gap-[24px]">
          {children}
        </div>
    </main>
  );
}
