import type { Metadata } from "next";
import '@/app/globals.css'

export const metadata: Metadata = {
  title: "Article Page",
  description: "Generated by create next app",
};

export default function ArticleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen w-full bg-white">
        {children}  
    </main>
  );
}
